//
//  orm.m
//  this file was generated by orm generator, don't modify it!
//
//  Created by jasenhuang on 15/8/14.
//  Copyright (c) 2015年 tencent. All rights reserved.
//

#import "orm.h"

@implementation WRBook (orm)
+ (id)instanceObject {
    return [[WRBook alloc] init];
}

+ (NSString *)dbName {
    return @"WRModelDatabase.db";
}

+ (NSString *)tableName {
    return @"WRBookTable";
}

+ (NSString *)primaryKey {
    return @"bookId";
}

+ (NSArray *)persistentProperties {
    static NSArray *properties;
    if (!properties) {
        properties = @[
    				@"bookId",
			    	@"title",
			    	@"author",
			    	@"intro",
			    	@"coverUrl",
			    	@"format"
			    	
			    	];
    }
    return properties;
}
@end

@implementation WRModel (orm)
+ (id)instanceObject {
    return [[WRModel alloc] init];
}

+ (NSString *)dbName {
    return @"WRModelDatabase.db";
}

+ (NSString *)tableName {
    return @"WRModelTable";
}

+ (NSString *)primaryKey {
    return @"bookId";
}

+ (NSArray *)persistentProperties {
    static NSArray *properties;
    if (!properties) {
        properties = @[
    				@"bookId",
			    	@"title",
			    	@"author",
			    	@"intro",
			    	@"coverUrl",
			    	@"format"
			    	
			    	];
    }
    return properties;
}
@end

